force-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <label>Resume</label>
    <nameField>
        <label>Resume Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume_Entry__c/Resume_Entry__c.object-meta.xml
<CustomObject>
    <label>Resume Entry</label>
    <nameField>
        <label>Resume Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resume Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume_Entry__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>Resume Entries</relationshipLabel>
    <relationshipName>Resume_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_Entry__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Aura</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>Azure</fullName>
            </value>
            <value>
                <fullName>BitBucket</fullName>
            </value>
            <value>
                <fullName>GCP</fullName>
            </value>
            <value>
                <fullName>GitHub</fullName>
            </value>
            <value>
                <fullName>GitLab</fullName>
            </value>
            <value>
                <fullName>Heroku</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Scratch Orgs</fullName>
            </value>
            <value>
                <fullName>SFDX</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>TypeScript</fullName>
            </value>
            <value>
                <fullName>Visualforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resume_Entry__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Job</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResumeSelector.cls
public with sharing class ResumeSelector {
  @AuraEnabled(cacheable=true)
  public static Id getResumeIdByName(String resumeName) {
    List<Resume__c> resumes = [
      SELECT Id
      FROM Resume__c
      WHERE Name = :resumeName
    ];
    if (resumes.size() > 1) {
      throw new UnexpectedException(
        'Multiple resumes found with the same name (' +
        resumeName +
        '). This confuses the c-resume-container because it does not know which resume to show.'
      );
    }

    return resumes.size() == 1 ? resumes[0].Id : null;
  }

  @AuraEnabled(cacheable=true)
  public static List<Id> getResumeEntryIds(Id resumeId, String type) {
    List<Id> resumeEntryIds = new List<Id>();
    for (Resume_Entry__c resumeEntry : [
      SELECT Id
      FROM Resume_Entry__c
      WHERE Resume__c = :resumeId AND Type__c = :type
      ORDER BY From__c DESC
    ]) {
      resumeEntryIds.add(resumeEntry.Id);
    }

    return resumeEntryIds;
  }

  @AuraEnabled(cacheable=true)
  public static String getUniqueSkillsFromResumeEntries(Id resumeId) {
    Set<String> skills = new Set<String>();
    for (Resume_Entry__c resumeEntry : [
      SELECT Skills__c
      FROM Resume_Entry__c
      WHERE Resume__c = :resumeId
    ]) {
      if (String.isEmpty(resumeEntry.Skills__c)) {
        continue;
      }

      for (String skill : resumeEntry.Skills__c.split(';')) {
        if (skills.contains(skill)) {
          continue;
        }

        skills.add(skill);
      }
    }

    // .sort() is a void method so we can't just return the constructed list
    List<String> result = new List<String>(skills);
    result.sort();

    // The UI expects this to look like a Multi-Select Picklist, so joining on semicolon
    return String.join(result, ';');
  }
}