force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Done__c.field-meta.xml
<CustomField>
    <fullName>Done__c</fullName>
    <description
  >Date the project was completed. This will only be updated to a new date if the status is set to a value other than Done and then updated to Done again.</description>
    <label>Done</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current state of the project.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectTriggerHandler.cls
public with sharing class ProjectTriggerHandler {
  private static final String STATUS_DONE = 'Done';

  public void onBeforeInsert(List<Project__c> projects) {
    for (Project__c project : projects) {
      if (isDone(project)) {
        setDone(project);
      }
    }
  }

  public void onBeforeUpdate(
    List<Project__c> projects,
    Map<Id, Project__c> idToOldProject
  ) {
    for (Project__c project : projects) {
      Project__c oldProject = idToOldProject.get(project.Id);
      if (project.Status__c != oldProject.Status__c) {
        if (isDone(project)) {
          setDone(project);
        } else {
          clearDone(project);
        }
      }
    }
  }

  private Boolean isDone(Project__c project) {
    return STATUS_DONE.equals(project.Status__c);
  }

  private void setDone(Project__c project) {
    project.Done__c = Date.today();
  }

  private void clearDone(Project__c project) {
    project.Done__c = null;
  }
}